# Shrink default JVM heap
esJavaOpts: "-Xmx512m -Xms512m"

# Allocate smaller chunks of memory per pod
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1200m"
    memory: "1G"

# Request smaller persistent volumes per pod (i.e. each pod here will take 10GB storage from the linode storage class)
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "linode-block-storage"
  resources:
    requests:
      storage: 100M
